services:
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=otel_password
      - MYSQL_DATABASE=db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./init.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test:
        mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ['--config=/etc/otel-collector.yaml']
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - 16686:16686

  example:
    build:
      dockerfile: $PWD/Dockerfile
      context: ..
    ports:
      - 2830:2830
    depends_on:
      mysql:
        condition: service_healthy
